; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
#NoTrayIcon     ;不显示托盘图标

;设置脚本所在位置为工作目录
SetWorkingDir %A_ScriptDir%
SetBatchLines -1


;GUI无最大化按钮、总在最前、无DPI缩放
Gui -MaximizeBox +AlwaysOnTop -DPIScale

;窗口大小，窗口标题
Gui Show, w971 h415, 名称

;文字大小，粗细，字体
Gui Font, s20 Bold, Arial
;文本类型，文本位置，字体种类，文本内容
Gui Add, Text, x321 y40 w328 h53 ,名称

;文字大小，粗细，字体
Gui Font, s9 Bold, Arial
;按钮触发变量，按钮位置与大小，按钮显示内容
Gui Add, Button, gbtnOriginal x126 y160 w167 h40, &按钮内容
Gui Add, Button, gbtnINI x678 y216 w167 h40, &按钮内容

;文字大小，字体
Gui Font, s7, Arial
Gui Add, Button, gbtnConfig x840 y352 w100 h35, &按钮内容

;文字大小，粗细，字体
Gui Font, s8 Bold, Arial
;文字颜色
Gui Font, c0xFF0000
Gui Add, Text, x160 y304 w651 h23 +0x200, 说明信息

Return

;变量具体代码
btnOriginal:
;最小化窗口
WinMinimize
;运行程序（Run为直接运行，RunWait为运行后等待进程结束再进行下一步）
Runwait ".\ComeOn.exe"
/*
;等待5秒
Sleep, 5000
;如果检测到EXE程序正在运行则激活该程序为活动窗口
if WinExist("ahk_exe ComeOn.exe")
WinActivate
;按下热键ALT+M
send, !M
*/
;退出程序
ExitApp

btnINI:
WinMinimize
;打开ini文件
RunWait ".\set.ini"
;恢复启动器
WinRestore
Return

btnConfig:
WinMinimize
RunWait ".\config.exe"
WinRestore
Return

GuiEscape:
GuiClose:
    ExitApp
